---
- name: Gather facts
  ansible.builtin.setup:

- name: Ensure Docker is installed
  block:
    - name: Check if Docker is installed
      ansible.builtin.command: which docker
      register: docker_installed
      ignore_errors: true
      changed_when: false

    - name: Install Docker if not installed
      ansible.builtin.package:
        name: docker
        state: present
      when: docker_installed.rc != 0

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

- name: Install required packages
  ansible.builtin.package:
    name: "{{ pkg }}"
    state: present
  loop:
    - git
    - python3
    - python3-pip
    - curl
    - jq
  loop_control:
    loop_var: pkg

- name: Check if elastic_container was already installed here
  ansible.builtin.stat:
    path: "{{ ludus_elastic_container_install_path }}/docker-compose.yml"
  register: elastic_container_installed

- name: Check Docker health status
  ansible.builtin.shell:
    cmd: >-
      docker ps --format '{{ "{{" }}json .{{ "}}" }}' |
      jq -r 'select(.Status | test("Up") | not) | .Names'
  register: docker_health_check
  changed_when: false
  failed_when:
    - docker_health_check.rc != 0
    - docker_health_check.stdout | length > 0
  args:
    executable: /bin/bash

- name: End the playbook if elastic is already installed
  ansible.builtin.meta: end_host
  when:
    - elastic_container_installed.stat.exists
    - docker_health_check.stdout | trim | length == 0

- name: Get the source code
  ansible.builtin.git:
    repo: https://github.com/peasead/elastic-container
    dest: "{{ ludus_elastic_container_install_path }}"
    version: "{{ elastic_container_branch }}"
    single_branch: true
    force: true

- name: Copy the .env template to the host
  ansible.builtin.template:
    src: files/env.example
    dest: "{{ ludus_elastic_container_install_path }}/.env"
    mode: "0600"

- name: Gather facts (need RAM of the host to dynamically allocate memory in bytes to .env)
  ansible.builtin.setup:

- name: Register memory of the host to replace in .env file and register only 75% of the memory
  ansible.builtin.set_fact:
    host_memory_bytes: "{{ ansible_memtotal_mb * 1024 * 1024 * 0.75 }}"

- name: Memory being used by Kibana
  ansible.builtin.debug:
    msg: "Host memory: {{ host_memory_bytes }}"

- name: Replace memreplaceme in .env file with the memory of the host
  ansible.builtin.replace:
    path: "{{ ludus_elastic_container_install_path }}/.env"
    regexp: "memchangeme"
    replace: "{{ host_memory_bytes }}"

- name: Replace stackreplace me in .env file with the ludus_elastic_stack_version
  ansible.builtin.replace:
    path: "{{ ludus_elastic_container_install_path }}/.env"
    regexp: "stackchangeme"
    replace: "{{ ludus_elastic_stack_version }}"

- name: Replace passchangeme in .env file with the ludus_elastic_password
  ansible.builtin.replace:
    path: "{{ ludus_elastic_container_install_path }}/.env"
    regexp: "passchangeme"
    replace: "{{ ludus_elastic_password }}"
    backup: true

- name: Move and replace kibana.yml file to the host
  ansible.builtin.copy:
    src: files/kibana.yml
    dest: "{{ ludus_elastic_container_install_path }}/kibana.yml"
    mode: "0644"

- name: Replace elastichostchangeme in files/kibana.yml file with the ansible_host
  ansible.builtin.replace:
    path: "{{ ludus_elastic_container_install_path }}/kibana.yml"
    regexp: "elastichostchangeme"
    replace: "{{ ansible_host }}"

- name: Replace passchangeme in files/kibana.yml files with the ludus_elastic_password
  ansible.builtin.replace:
    path: "{{ ludus_elastic_container_install_path }}/kibana.yml"
    regexp: "passchangeme"
    replace: "{{ ludus_elastic_password }}"

- name: "Running ./elastic-container.sh start in the directory: {{ ludus_elastic_container_install_path }}"
  ansible.builtin.command: ./elastic-container.sh start
  args:
    chdir: "{{ ludus_elastic_container_install_path }}"
  register: elastic_container_start
  timeout: 500
  ignore_errors: true
  changed_when: true

- name: Wait for the container to be listening on port 5601
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 5601
    state: started
    delay: 30
    timeout: 300
    sleep: 5
  register: wait_result
  failed_when: wait_result.elapsed > 300 or wait_result.state != 'started'

- name: Get Elastic agents if needed
  run_once: true
  block:
    - name: Create /opt/ludus/resources/elastic directory if it doesn't exist
      ansible.builtin.file:
        path: /opt/ludus/resources/elastic
        state: directory
        recurse: true
      delegate_to: localhost

    - name: Check if Windows agent exists
      ansible.builtin.stat:
        path: /opt/ludus/resources/elastic/elastic-agent-{{ ludus_elastic_stack_version }}-windows-x86_64.zip
      delegate_to: localhost
      register: windows_agent_exists

    - name: Download the Windows agent
      ansible.builtin.get_url:
        url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ ludus_elastic_stack_version }}-windows-x86_64.zip"
        dest: /opt/ludus/resources/elastic/elastic-agent-{{ ludus_elastic_stack_version }}-windows-x86_64.zip
        mode: "0644"
      delegate_to: localhost
      when: not windows_agent_exists.stat.exists

    - name: Check if Linux agent exists
      ansible.builtin.stat:
        path: /opt/ludus/resources/elastic/elastic-agent-{{ ludus_elastic_stack_version }}-linux-x86_64.tar.gz
      delegate_to: localhost
      register: linux_agent_exists

    - name: Download the Linux agent
      ansible.builtin.get_url:
        url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ ludus_elastic_stack_version }}-linux-x86_64.tar.gz"
        dest: /opt/ludus/resources/elastic/elastic-agent-{{ ludus_elastic_stack_version }}-linux-x86_64.tar.gz
        mode: "0644"
      delegate_to: localhost
      when: not linux_agent_exists.stat.exists

- name: Move kibana-setup.py file to the host
  ansible.builtin.copy:
    src: files/kibana-setup.py
    dest: "{{ ludus_elastic_container_install_path }}/kibana-setup.py"
    mode: "0700"

- name: Replace values in kibana-setup.py file
  ansible.builtin.replace:
    path: "{{ ludus_elastic_container_install_path }}/kibana-setup.py"
    regexp: "fleetserverchangeme"
    replace: "{{ ansible_host }}"
    backup: true

- name: Move requirements.txt file to the host
  ansible.builtin.copy:
    src: files/requirements.txt
    dest: "{{ ludus_elastic_container_install_path }}/requirements.txt"
    mode: "0600"

- name: Print major version
  ansible.builtin.debug:
    msg: "OS Version: {{ ansible_distribution_major_version }}"

- name: Install the required python packages on Debian 12
  ansible.builtin.pip:
    requirements: "{{ ludus_elastic_container_install_path }}/requirements.txt"
    executable: pip3
    extra_args: --break-system-packages
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '12'

- name: Install the required python packages on Debian 11
  ansible.builtin.pip:
    requirements: "{{ ludus_elastic_container_install_path }}/requirements.txt"
    executable: pip3
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'

- name: Check port 5601 one more time if it failed before
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 5601
    state: started
    delay: 30
    timeout: 300
    sleep: 5

- name: Run kibana-setup.py
  ansible.builtin.command: python3 ./kibana-setup.py
  args:
    chdir: "{{ ludus_elastic_container_install_path }}"
  register: kibana_setup
  ignore_errors: true
  changed_when: false

- name: Get the elastic token
  ansible.builtin.slurp:
    path: "{{ ludus_elastic_container_install_path }}/enrollment_token.txt"
  register: token_slurp

- name: Output the kibana-setup.py output
  ansible.builtin.debug:
    msg: "{{ kibana_setup.stdout_lines }}"

- name: Inform the user that the Elastic Container Project is up and running
  ansible.builtin.debug:
    msg: |
      Elastic Container Project is up and running. Access it at https://{{ ansible_host }}:5601 Access with: elastic:{{ ludus_elastic_password }}
      To add agents, use the token: {{ token_slurp['content'] | b64decode }}
